-- 19/08/2015 VEILLET

-- Contrôle le fichier log des traitements

SELECT * FROM WWFUSDTF.FUS1LOGPF
WHERE DATE(C_DATEHEURE) = CURRENT_DATE
AND C_PROGRAMME = 'FUS00401'
AND C_LOGLEVEL IN ('ERROR','FATAL');

SELECT * FROM WWSRISQF.SRI1LOGPF
WHERE DATE(C_DATEHEURE) = CURRENT_DATE
AND C_PROGRAMME = 'SRI90004'
AND C_LOGLEVEL IN ('ERROR','FATAL');

SELECT * FROM WWADHESF.ADH1LOGPF
WHERE DATE(C_DATEHEURE) = CURRENT_DATE
AND C_PROGRAMME = 'ADH90004'
AND C_LOGLEVEL IN ('ERROR','FATAL');

SELECT * FROM WWSINISF.SIN1LOGPF
WHERE DATE(C_DATEHEURE) = CURRENT_DATE
AND C_PROGRAMME = 'SIN90004'
AND C_LOGLEVEL IN ('ERROR','FATAL');

SELECT * FROM WWSESINF.SES1LOGPF
WHERE DATE(C_DATEHEURE) = CURRENT_DATE
AND C_PROGRAMME = 'SES90004'
AND C_LOGLEVEL IN ('ERROR','FATAL');

SELECT * FROM ITADCQSF.ADC1LOGPF
WHERE DATE(C_DATEHEURE) = CURRENT_DATE
AND C_PROGRAMME = 'ADC90004'
AND C_LOGLEVEL IN ('ERROR','FATAL');

SELECT * FROM ITSICQSF.SIC1LOGPF
WHERE DATE(C_DATEHEURE) = CURRENT_DATE
AND C_PROGRAMME = 'SIC90004'
AND C_LOGLEVEL IN ('ERROR','FATAL');

SELECT * FROM FRAHEMPF.AHE1LOGPF
WHERE DATE(C_DATEHEURE) = CURRENT_DATE
AND C_PROGRAMME = 'AHE90004'
AND C_LOGLEVEL IN ('ERROR','FATAL');

SELECT * FROM WWPIECEF.PIE1LOGPF
WHERE DATE(C_DATEHEURE) = CURRENT_DATE
AND C_PROGRAMME = 'PIE90004'
AND C_LOGLEVEL IN ('ERROR','FATAL');

SELECT * FROM BIBCOMMU.A1ILOGPF
WHERE DATE(C_DATEHEURE) = CURRENT_DATE
AND C_PROGRAMME = 'CBP90004'
AND C_ERREURSQL <> 100;

SELECT * FROM WWBSADHF.BSA1LOGPF
WHERE DATE(C_DATEHEURE) = CURRENT_DATE
AND C_PROGRAMME = 'BSA90004'
AND C_LOGLEVEL IN ('ERROR','FATAL');
